### ISSUE TITLE
dr_wav 0.13.2: clang flagged issues

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#207]
The recent commit caused Clang to flag 12 new issues:

![2021-10-02_10-17](https://user-images.githubusercontent.com/1557255/135729692-7e8699f1-091b-4ff9-b12e-8f85043cb307.png)

Open the following `index.html` and sort by file to see the `dr_wav.h` block of new issue:

[dr_wav-0.13.2-clang-issues.tar.gz](https://github.com/mackron/dr_libs/files/7272097/dr_wav-0.13.2-clang-issues.tar.gz)

Also happy to open separate tickets, if it's easier to track.

**Comment by mackron** [comment]
The dead assignments should be fixed now in the dev branch. The others are more complicated. I'm not quite sure what's going on there. I'm hesitant to call these a false positive, but I've rearranged the code just a little bit to see if maybe it might silence those errors. I feel like these particular errors would be more useful with a sample file so I can inspect the data in a debugger.

**Comment by kcgen** [comment]
Will run the latest through tomorrow am and report back; thanks @mackron.

**Comment by kcgen** [comment]
Here's the new analysis, and 3 issues have been solved as you were expecting. 

https://github.com/dosbox-staging/dosbox-staging/suites/3969999617/artifacts/99801415

Unfortunately the static analyzer doesn't use sample inputs (otherwise I would gladly send it/them along).

**Comment by mackron** [comment]
I've pushed another change to the dev branch with some potential fixes for the remaining warnings. If this doesn't work, I'm not sure what else I can do to fix these. I've added some validation to ensure the number of samples cannot exceed the temp buffer which should act as a guard. Are you able to give that another run?

**Comment by kcgen** [comment]
Thanks for continuing to try to solve these @mackron !
The update takes care of another couple issues.
I've attached the updated report:

[clang-analysis-report.zip](https://github.com/mackron/dr_libs/files/7579895/clang-analysis-report.zip)

Do the dr_libs have unit tests that can be compiled with gcc or clang? This would let me run the analyzer again just those test binaries to get an isolated analysis.

**Comment by mackron** [comment]
Thanks for that. Looks like it didn't fix anything. Very annoying. I have no idea what's going on with these ones.

These are the tests I use. They have some dependencies for the purpose of correctness benchmarking, however: https://github.com/mackron/dr_libs/tree/master/tests

**Comment by mackron** [comment]
I can think of one easy way to silence this error, and that is to clear the relevant buffer to 0 so that it's not treated as garbage, but I don't want to 1) mask a potential underlying bug; and 2) incur the inefficiency of clearing the buffer.

**Comment by kcgen** [comment]
Is the `sampleData` or `pIn` uninitialized, and the analyser's found the first pass where it's being read in this uninitialized state?

Is it possible to initialize the buffer to zero just one time during setup? (Assuming a static buffer?)

Another thought: if we know or rely on the uninitialized buffer value(s) being zero and not garbage, then we can assert that state (say, for the [0] element) and not expend the cycles to clear that memory (even once).

**Comment by mackron** [comment]
This line will fill `sampleData` at the start of the loop before anything touches it:
```c
drwav_uint64 framesRead = drwav_read_pcm_frames(pWav, framesToReadThisIteration, sampleData);
```
I thought maybe the return value (`framesRead`) is different to what is actually written to `sampleData`, but the implementation of `drwav_read_pcm_frames()` looks OK to my eye.

Putting `sampleData` into static space is not an option because it'll break when multiple `drwav` instances are running across multiple threads. Not only that, I don't want the added memory usage.

I'm thinking if this is a false positive. Take the Clang report on line 6288 (drwav_s32_to_s16). Go back to item 21 (Calling 'drwav_read_pcm_frames'). Item 40 says "Assuming 'framesRead' is not equal to 0". Now, move forward through the chain starting from 21, and go into `drwav_read_raw()` and observe item 36 which is the `return 0;` line. If you follow that back, it should be impossible for `framesRead` to be anything other than 0, right? Or am I missing something? If `drwav_read_raw()` is returning 0 (it returns the number of bytes read), how is it that `drwav_read_pcm_frames()` is returning anything other than 0?

**Comment by kcgen** [comment]
> I'm thinking if this is a false positive. Take the Clang report on line 6288 (drwav_s32_to_s16). Go back to item 21 (Calling 'drwav_read_pcm_frames'). Item 40 says "Assuming 'framesRead' is not equal to 0". Now, move forward through the chain starting from 21, and go into drwav_read_raw() and observe item 36 which is the return 0; line. If you follow that back, it should be impossible for framesRead to be anything other than 0, right? 

Yes - this is also where I got confused.  

>  go into drwav_read_raw() and observe item 36 which is the return 0; line.

Indeed; when we get back up to the `while` loop, the next check will detect the zero-value and break out of the while loop, so I'm not sure how execution can get into the latter portion where the 'junk' data is assigned.

I can't try to suppress these.

**Comment by kcgen** [comment]
Just for interest sake, I [zero-initialized the buffers](
https://github.com/dosbox-staging/dosbox-staging/commit/cb20259244f1158194591d058205d1d7544deabe) and adjacent counters, which surprisingly fixed that class of bugs.

And followed up with another [minor commit](https://github.com/dosbox-staging/dosbox-staging/commit/94c725cc553e4c2f04ad0e737e98e2931ddd54c0) took care of the remaining three.

Here's the [clang-analysis-report.zip](https://github.com/dosbox-staging/dosbox-staging/suites/4435943964/artifacts/117516287)

**Comment by mackron** [comment]
The dead assignment errors were fixed earlier when you first posted this issue.

I've pushed to the dev branch a change to initialize the temp buffers to 0.

**Comment by kcgen** [comment]
That's got them all; not a single dr_lib is flagged now :+1: 

[clang-analysis-report.zip](https://github.com/mackron/dr_libs/files/7589634/clang-analysis-report.zip)

Thank you @mackron !

**Comment by mackron** [comment]
Thanks for confirming that for me. This has been released.
